name: Windows Build with Qt & MSVC (Manual - Ninja)

on:
  workflow_dispatch:

env:
  QT_VERSION: 6.8.1
  BUILD_TYPE: Release
  BUILD_DIR: ${{ github.workspace }}/build
  VCPKG_ROOT: C:\vcpkg

jobs:
  build:
    runs-on: windows-latest

    steps:
      # ------------------------------------------------------------
      # Checkout
      # ------------------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # ------------------------------------------------------------
      # Qt
      # ------------------------------------------------------------
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_msvc2022_64
          cache: true

      # ------------------------------------------------------------
      # MSVC
      # ------------------------------------------------------------
      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      # ------------------------------------------------------------
      # Ninja
      # ------------------------------------------------------------
      - name: Install Ninja
        run: choco install ninja -y
        shell: pwsh
        
      - name: Inspect vcpkg
        run: |
           echo VCPKG_ROOT=%VCPKG_ROOT%
           "%VCPKG_ROOT%\vcpkg.exe" version
           "%VCPKG_ROOT%\vcpkg.exe" help x-update-baseline
        shell: cmd
       
      # ------------------------------------------------------------
      # Configure
      # ------------------------------------------------------------
      - name: Configure with Ninja
        run: >
          cmake -B "%BUILD_DIR%"
          -G "Ninja"
          -DCMAKE_BUILD_TYPE="%BUILD_TYPE%"
          -DCMAKE_TOOLCHAIN_FILE="%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake"
          -DVCPKG_TARGET_TRIPLET=x64-windows
        shell: cmd
        env:
          BUILD_DIR: ${{ env.BUILD_DIR }}
          BUILD_TYPE: ${{ env.BUILD_TYPE }}

      # ------------------------------------------------------------
      # Build
      # ------------------------------------------------------------
      - name: Build with Ninja
        run: |
          cmake --build "%BUILD_DIR%"
        shell: cmd
        env:
          BUILD_DIR: ${{ env.BUILD_DIR }}
